version: '3'
services:

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    hostname: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  producer:
    image: "microservice-calculator-example"
    container_name: producer
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: producer
      server.port: 8080
      spring.kafka.bootstrap-servers: kafka:9092

  consumer:
    image: "microservice-calculator-example"
    container_name: consumer
    environment:
      SPRING_PROFILES_ACTIVE: consumer
      spring.kafka.bootstrap-servers: kafka:9092